# Generated by Django 2.2 on 2019-04-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actividad', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=29)),
            ],
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='ide',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='timer',
        ),
    ]
