# Generated by Django 2.2 on 2019-04-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acora', '0002_auto_20190417_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='cod',
            field=models.CharField(default='o0', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='idRanking',
            field=models.CharField(default='0o0', max_length=200, primary_key=True, serialize=False),
        ),
    ]
