# Generated by Django 2.2 on 2019-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acora', '0003_auto_20190417_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(default='0j0', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idComentario', models.CharField(default='esto es un comentario', max_length=200)),
                ('puntuacionUno', models.IntegerField(default=0)),
                ('puntuacionDos', models.IntegerField(default=0)),
                ('puntuacionTres', models.IntegerField(default=0)),
            ],
        ),
    ]
