# Generated by Django 2.2 on 2019-04-30 12:16

import acora.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acora', '0004_codigos_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='codigo',
            field=models.ForeignKey(default=acora.models.getCod, on_delete=django.db.models.deletion.CASCADE, to='acora.Partida'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='puntaje',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
