# Generated by Django 2.2 on 2019-04-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acora', '0006_remove_equipo_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='idPista',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='puntaje',
        ),
    ]
