# Generated by Django 2.2 on 2019-04-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acora', '0007_auto_20190430_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(default='sinNombre', max_length=200, unique=True),
        ),
    ]
