# Generated by Django 2.2 on 2019-04-30 12:37

import acora.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acora', '0009_auto_20190430_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='codigo',
            field=models.ForeignKey(default=acora.models.getCod, on_delete=django.db.models.deletion.CASCADE, to='acora.Partida'),
        ),
    ]
