# Generated by Django 2.2 on 2019-05-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acora', '0015_auto_20190430_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='cod',
            field=models.CharField(blank=True, default='o0', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(default='sinNombre', max_length=200),
        ),
    ]
